### ISSUE TITLE
Show hidden properties if many

### ISSUE THREAD

**Issue by perrauda** [geovistory/design-system#105]
In geov-entity, particularly in nested properties, 

when there are several properties, do not display the value, but **indicate only the number of properties available.**

This number can be clicked and **opens a modal window displaying geov-entity-props-by-predicate (with 10 lines per page to start with)**

**Comment by joschne** [comment]
> ... do not display the value ...

Ah, this is a good idea. It did not occur to me, to hide the value. What would you show instead? The number of items (see below)?

Before
![image](https://github.com/geovistory/design-system/assets/10991869/742abbfa-2819-4a3a-af26-a4b06eb04e7e)

After
![image](https://github.com/geovistory/design-system/assets/10991869/be60fe1c-6438-41ee-8356-e3f6c31c4481)

**Comment by perrauda** [comment]
Yes, it's exactly what I imagined
