### ISSUE TITLE
Show properties of an entity

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#28]
## Goal
A web component that displays all the properties of a Geovistory Entity. 

This component can be used on entity pages like these, to generically display the data:

- Ship voyage from Texel to Jakarta: [https://www.geovistory.org/page/i151089](https://www.geovistory.org/page/i151089)
- Person Johannes Kepler: [https://www.geovistory.org/page/i785518](https://www.geovistory.org/page/i785518)

Remark: This component has to be seen as a generic view on the data, that will be complemented by class specific components. 

## Shape of the Data

All properties to display are serialized as RDF. RDF is based on the concept of triples consisting of subject, predicate and object. Our triples have this shape:

**subject** is always a URI (by RDF specification)
- for this issue, we are only interested in URI's starting with `http://geovistory.org/resource/i`

**predicate** is always a URI (by RDF specification)
- the majority starts with `https://ontome.net/ontology/p`
- there are some other widely used predicates, like 
  - `http://www.w3.org/2002/07/owl#sameAs` (owl:sameAs)
  - `http://www.w3.org/2000/01/rdf-schema#label` (rdfs:label)
  - `http://www.w3.org/1999/02/22-rdf-syntax-ns#type` (rdf:type)

**object** can be a URI or a Literal (by RDF specification). 
- URI
  - majority starts with `http://geovistory.org/resource/i`
  - in combination with `owl:sameAs` there are external URIs like `https://www.idref.fr/027446336/id>` or `https://dbpedia.org/resource/Heidelberg`
  - in combination with `rdf:type` there are URIs starting with `https://ontome.net/ontology/c`
- Literal (see [syntax for literals](https://www.w3.org/TR/sparql11-query/#QSynLiterals))
  - language strings
  @en, @de, @fr, ect.
  - strings (using prefix xsd: http://www.w3.org/2001/XMLSchema#)
  ^^xsd:string
  - spatial data (using prefix geo: http://www.opengis.net/ont/geosparql#)
  ^^geo:wktLiteral
  - temporal data (using prefix time: http://www.w3.org/2006/time#)
  ^^time:DateTimeDescription
  ^^time:hasTRS
  ^^time:unitType
  ^^time:day
  ^^time:month
  ^^time:year

## Specs

The web component exposes these properties (`@Prop()`)
- `entityId: string` the input for the entity id
- `sparqlEndpoint: string` the input for the sparql endpoint url
- `fetchBeforeRender: boolean = true` if true, componentWillLoad() returns a promise for the loading of all data [default: true]
- `langage: string = en` input to pass in the preferred language to the component, default 'en'.

The web component renders the incoming and outgoing properties of the entity with the given `entityId`, provided by the sparql endpoint given by `sparqlEndpoint`. 

The web component prints the label with the `language` or english, if not found. 
Implement the rendering of labels always as if there could be many labels, concatenating them with ', '.

The web component uses [ionic list](https://ionicframework.com/docs/api/list), [ionic item](https://ionicframework.com/docs/api/item) and related components for the UI.

The web component renders the URIs as links, wherever possible. Links open in new window (target=_blank)

The web component has to deal with performance: Limit the number of queries, if possible. Limit the number of properties with the same predicate (max page size 10) and allow user to paginate.

The web component may be decomposed in many web components, if this makes sense for the code maintainability and for the loading performance. As a rule of thumb: Many small components are easier to understand and maintain, then one big component. A component should not have more than 200 lines of code. Reusable functions may also be excluded to /lib.

The mockups below show the different cases we'll encounter, together with some queries used to create the mockups.

#### Mockup
![texel ship voyage](https://user-images.githubusercontent.com/10991869/195328398-f12c69f0-b7a1-44b7-aa42-e6a275b83675.png)
#### Queries
Outgoing triples of Ship Voyage geov:i151089, including pedicate label, object label and data type of literal:
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT ?subject ?predicate ?predicateLabel ?object ?objectLabel ?dt
WHERE {
  geov:i151089 ?predicate ?object .
  ?predicate rdfs:label ?predicateLabel.
  OPTIONAL {?object rdfs:label ?objectLabel.}
  BIND (datatype(?object) AS ?dt)
}
LIMIT 20
``` 

#### mockup

![texel geographical place](https://user-images.githubusercontent.com/10991869/195333613-5406d14c-6344-4067-81ae-a9efc3b0586f.png)

#### queries
outgoing props
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT ?subject ?predicate ?object ?dt
WHERE {
  geov:i209502 ?predicate ?object .
  BIND (datatype(?object) AS ?dt)
}
LIMIT 10
```

incomig property count
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT   ?predicate (count(distinct ?subject) as ?count) 
WHERE {
 ?subject ?predicate geov:i209502 .
}
GROUP BY ?predicate 
LIMIT 100
```

limited incoming property ontome:p1336
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT   ?subject
WHERE {
 ?subject ontome:p1336 geov:i209502 .
}
LIMIT 10
```
#### mockup
![presence](https://user-images.githubusercontent.com/10991869/195337639-e449067e-5128-4704-ae40-ec1fd64e605c.png)

#### queries
Props of geov:i253594
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT ?predicate ?object ?dt
WHERE {
  geov:i253594 ?predicate ?object .
  BIND (datatype(?object) AS ?dt)
}
LIMIT 10
```

#### mockup
![time span](https://user-images.githubusercontent.com/10991869/195339898-759510d1-22de-4e22-8006-6d49a6ebc72c.png)

#### queries
Properties of time span
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT ?subject ?predicate ?object ?dt
WHERE {
  geov:i151089ts ?predicate ?object .
  BIND (datatype(?object) AS ?dt)
}
LIMIT 10
```
Properties of [time:DateTimeDescription](http://www.w3.org/2006/time#DateTimeDescription)
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX ontome: <https://ontome.net/ontology/>
PREFIX geov: <http://geovistory.org/resource/>

SELECT ?subject ?predicate ?object ?dt
WHERE {
geov:i271905 ?predicate ?object .
  BIND (datatype(?object) AS ?dt)
}
LIMIT 10
```

**Comment by joschne** [comment]
@atterebf please review this spec from stakeholder perspective. Is it meeting the expectations?
@perrauda please review this spec from a developer perspective. Is it clear?

**Comment by perrauda** [comment]
Everything is good for me, very clear.

**Comment by atterebf** [comment]
This one in fact for triples without labels:

SELECT ?subject ?predicate ?predicateLabel ?object ?objectLabel ?dt
WHERE {
  geov:i151089 ?predicate ?object .
  ?predicate rdfs:label ?predicateLabel.
  OPTIONAL {?object rdfs:label ?objectLabel.}
  BIND (datatype(?object) AS ?dt)
}
LIMIT 20

**Comment by joschne** [comment]
> This one in fact for triples without object's label:
> 
> SELECT ?subject ?predicate ?predicateLabel ?object ?objectLabel ?dt WHERE { geov:i151089 ?predicate ?object . ?predicate rdfs:label ?predicateLabel. OPTIONAL {?object rdfs:label ?objectLabel.} BIND (datatype(?object) AS ?dt) } LIMIT 20

Indeed, this is very good. And this query shows another issue: We may have multiple labels for predicates, here:
ontome:p4 -> "hat Zeitspanne"@de
ontome:p4 -> "has time-span"@en

I suggest 

1. We add a `@Prop() language = 'en'` input to pass in the preferred language to the component, default 'en'.
2. The component prints the label with the `language` or english, if not found.
3. Implement the rendering of labels always as if there could be many labels, concatenating them with ', '.

**Comment by perrauda** [comment]
OK I understand your suggestion and I have added them to the spec as well as the modification of the query (Francesco)

**Comment by joschne** [comment]
In order to show inverse property labels, they are needed in the RDF.

See the discussion https://github.com/geovistory/rdf-serialization/issues/26

with the specified solution it should be possible to fetch the inverse label in this query:

```typescript
const qrIncomingPropsWithCount = (id: string) => `

...

SELECT   ?predicate ?predicateLabel (count(distinct ?subject) as ?count)
WHERE {
 ?subject ?predicate geov:${id} .
 ?predicate rdfs:label ?predicateLabel
}
GROUP BY ?predicate ?predicateLabel
LIMIT 100
`;
```

by appending "i" to the predicate label (pseudo code):


```typescript
...

SELECT   ?predicate ?predicateLabel (count(distinct ?subject) as ?count)
WHERE {
 ?subject ?predicate geov:${id} .
 ?predicate:i rdfs:label ?predicateLabel
}
```
