### ISSUE TITLE
Create a tutorial for non JS/TS dev to create a Data Visualization web component

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/design-system#41]
The goal is to create a accurate enough tutorial to allow people that only have notions of javascript/typescript to develop data visualization web component, so that there is very little help required from someone else.

**Comment by perrauda** [comment]
Review ok

**Comment by joschne** [comment]
Hi @gaetanmuck and @perrauda, I love the tutorial you wrote! 

The issue can only be set to validation done, if it is also deployed on production.

Is it correct, that the tutorial is not yet on production?

If so, can you @gaetanmuck please update the status and assignee of the issue and organize the next steps to finish the issue (i.e. to deploy it on prod.)?
