### ISSUE TITLE
Explorer > Add preferred classes

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#46]
### Current situation

The entity explorer shows a class filter to the left, in which the classes are ordered by number of entities found for this class, in descending order.

The classes shown on top of the list are usually not the ones, expected by users (like Appellation in a language or Annotation in Text).
![image](https://user-images.githubusercontent.com/10991869/233098786-30af6ceb-6f28-4266-b5ed-8ef2167c265f.png)

### Solution

The class filter is split in two lists:
- a list with preferred classes
- a list with all classes 

To define the list of preferred classes, the component accepts a comma separate list of class ids.
The order of the ids is respected in the display.

**Only preferred classes visible; no class selected**
![MacBook Air - 2](https://user-images.githubusercontent.com/10991869/232078584-971f9ca2-2f9b-4ad7-829e-b5c9feecb1d6.png)

**All classes visible; no class selected**
 ![MacBook Air - 3](https://user-images.githubusercontent.com/10991869/232078582-4568ece3-7310-45aa-a371-ee67c001fcc5.png)

**All classes visible; Class Person selected**
![MacBook Air - 4](https://user-images.githubusercontent.com/10991869/232078578-24a365c5-bf94-4474-9895-d5f09b0e7e7f.png)

**Interactions**
- On click on `Show all classes` all classes are shown. The all classes list contains all classes, including the preferred.

- On click on `Hide` the list with all classes is hidden.

- On click on a class, a checkmark appears and the chip with the selected class appears. The chip ensures the selected filter is visible, even if the selected class is not visible to the left.

- On click on the Chip, the filter is deactivated (class unselected).

**Comment by joschne** [comment]
@KleiolabDK please review

**Comment by KleiolabDK** [comment]
Thank you, this is in line with the suggestions. Review closed.

**Comment by flicksolutions** [comment]
I added PR#56 which adds the preferred list. It does not add the "tags" since I have an open question to that.
Adding tags at the top like so
![grafik](https://user-images.githubusercontent.com/33655122/235903788-d2b468db-95a4-4c19-8d27-d4d03eec7196.png)
implies that you can select multiple filters. Is that the case?
