### ISSUE TITLE
Authority lookup webcomponent

### ISSUE THREAD

**Issue by perrauda** [geovistory/design-system#57]
## Goal
A webcomponent `geov-authority-lookup` which we can lookup URI entities from authority files (Wikidata and GND)

## Spec

Two webcomponents: `geov-authority-lookup` and `geov-authority-lookup-explorer`
This will use lobid (for gnd) and SPARQL (for Wikidata). See Confluence documentation.

### geov-authority-lookup-explorer

It's just a mini webcomponent which only a certain number of best occurences from a result of API can be display.

**Mockup**
![Image](https://github.com/geovistory/design-system/assets/5019779/d65cd874-e42a-4ed4-91ec-fd5e46d116d2)
(The 'Open' button will be 'clear' and accompanied by an 'open' button)

**Features:**
With three buttons, we can copy, select or access the uri.

Select: The user can select an item. This emits the selected URI in an event on geov-authority-lookup.
Open: The user can open the website of the item in a new browser tab.
Copy: The user can copy the URI to the clipboard. (not available by default)

Inputs:

- api (e.g. 'wikidata' or 'gnd')
- keywords
- type (can be null)
- nbOccurencesMax (by default: 5) the number of occurences on display
- listButtons (by default ['select', 'open']) (other possible value in this list: 'copy')

### geov-authority-lookup

It's a webcomponent which the previous webcomponent can be used there. 
The webcomponent will mainly be completed with a search field, a type selection and a button.

**Mockup**
![Image](https://github.com/geovistory/design-system/assets/5019779/a3f63d7d-05f0-4e35-86b6-250fdb0dae3c)

On mobile
![Image](https://github.com/geovistory/design-system/assets/5019779/71c8a1ec-fd67-4e91-8a7e-5a114df9f452)

Inputs
- list of type (**Person, Place, Group** to start)
- list of authority we want use (by default, 'gnd', 'wikidata')

## Examples of data with API

**Wikidata:**

https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22www.wikidata.org%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3Aapi%20%22EntitySearch%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mwapi%3Asearch%20%22Kepler%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mwapi%3Alanguage%20%22en%22.%0A%20%20%20%20%20%20%3Fitem%20wikibase%3AapiOutputItem%20mwapi%3Aitem.%0A%20%20%20%20%20%20%3Fnum%20wikibase%3AapiOrdinal%20true.%0A%20%20%7D%0A%20%20%3Fitem%20rdfs%3Alabel%20%3Fname%20filter%20%28lang%28%3Fname%29%20%3D%20%22en%22%29.%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5%0A%7D%20ORDER%20BY%20ASC%28%3Fnum%29%20LIMIT%2020

We can use item & name.

**GND (lobid)**
https://lobid.org/gnd/search?q=Johan,Kepler&filter=type:Person&format=json:preferredName

Returns (partial data):

```json

    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Johannes%20Kepler.jpg?width=100",
    "label": "Kepler, Johannes",
    "id": "https://d-nb.info/gnd/118561448",
    "category": "Individualisierte Person"
```
We can use label & id.

**IdRef**
additional integration: idref
https://documentation.abes.fr/aideidrefdeveloppeur/index.html#UtiliserApiSolr

https://www.idref.fr/Sru/Solr?q=geogname_t:(Lyon)&start=0&rows=5&indent=on&sort=score%20desc&fl=id,ppn_z,affcourt_z&version=2.2&wt=json

We can use ppn_z (for concatenate URI, no alternative) & affcourt_z (label)

**Comment by perrauda** [comment]
Thank you, the specifications have been modified following your comment. Is it ok?
On my side OK for SPARQL, I will study it a little more in the meantime.

**Comment by joschne** [comment]
Perfect. 

A thought: Both buttons now have the same style. I think, select is the primary action, open the secondary. To reflect this hierarchy visually, you could set the fill of "Open" to "clear". In addition, you could add a open icon (the one you had before) to the end of the button.

Question: What "types" would you start with? I suggest to start with Person, Place and Group. The mapping to GND and Wikidata Types is then to be done during implementation.

**Comment by perrauda** [comment]
Ok for the buttons, I note that.

Types:
Ok for types, we start with Person, Place and Group.
List of types in GND (However several types are subclasses): https://d-nb.info/standards/elementset/gnd
Wikidata it's more complicated to find a list of types, we need to find one by one I think, no problem with this three types.

In GND explorer we could see the list of types they were using (8 or 9) but the website is currently down.

**Comment by joschne** [comment]
Ok, spec review is finished from my side

**Comment by perrauda** [comment]
@KleiolabDK 
Hello, the webcomponent is ready, just as you asked, and you can now do a review for the UX aspect.

Here is the doc: https://design-dev.geovistory.org/?path=/docs/data-components-authority-lookup--basic
You'll find different stories, all can be tested

**Comment by KleiolabDK** [comment]
thank you @perrauda this looks great!

For me, the functionalities are fine. Just two comments:

1. short response when clicking "select"

In order to improve the authority lookup explorer, when clicking select nothing visible happens. a small user feedback like "you have selected id1111" would be helpful.

2. in the  authority lookup explorer, it would be good to enable "copy" by default

![image](https://github.com/geovistory/design-system/assets/51605237/1f31fd91-fe95-4149-ba01-cbe9d4d25b91)

**Comment by KleiolabDK** [comment]
my comments are regarding the documentation:

describe somehwere which APIs are available for this webcomponent and how they can be called/connected (idref, gnd, wikidata)
![image](https://github.com/geovistory/design-system/assets/51605237/00a1db3a-d7dc-41a7-8467-a6dabfcfcbb6)

**Comment by KleiolabDK** [comment]
authority lookup explorer:

it is not clear what the part "stories" is for. if not needed, better to delete it:
![image](https://github.com/geovistory/design-system/assets/51605237/373a9dcc-e0fc-44b6-ba7e-b01dcb241c3d)

**Comment by KleiolabDK** [comment]
explain here the available buttons and what they do:

![image](https://github.com/geovistory/design-system/assets/51605237/98731a5c-e0f5-4cc7-a7b9-ba8775362800)

**Comment by KleiolabDK** [comment]
elaborate a bit more hwo the selection of the type/class can help to refine search results (maybe with an example)

![image](https://github.com/geovistory/design-system/assets/51605237/33071aff-2b7d-43fc-bbd1-5027259e5a75)

**Comment by KleiolabDK** [comment]
Regarding the APIs, we have currently GND, idref and wikidata. I would suggest to include the API of Geovistory Public. I am aware that this is a new requirement, but given the estimate from Alexandre that this can be done in 1 day, I think it would be great.

**Comment by joschne** [comment]
> ### **comment 1 DK**
Agreed:
- For Select button: We add a `alert("you selected "+ uri)`
- We activate the Copy button in the first story (Playground).

**Comment by joschne** [comment]
> comment 2 DK

It is not so easy to add a link to the left. We agreed to try to make a link to the left. If it is not possible, we add a link to "Component API" to the introduction text.

**Comment by joschne** [comment]
> comment 3 DK

Since we don't need the stories of geov-authority-lookup-explorer, we delete them.

**Comment by joschne** [comment]
> ### **comment 5 DK**

We add a table explaining what the type-filter does on each API:

![image](https://github.com/geovistory/design-system/assets/10991869/7359db6f-d27d-4f53-8d3a-42c10e1357ca)

**Comment by joschne** [comment]
> ### **comment 6 DK**

Agreed.

We add geovistory api. In the second line of each search result we put:
{class label} – {entity id}

E.g.
Mozart
Person – i123123

**Comment by joschne** [comment]
> ### **comment** 4 DK

```
     ...
     It is maintained by the Bibliographic Agency for Higher Education (ABES) in France.

<- ADD THE FOLLOWING TEXT HERE ->

The component has a rich API for customization and styling, see below.
```

Supported user actions:
1. Filter the authority files by search terms (full text) and type
2. View a ranked list of entities.
3. Click on one of the following buttons:
  - **Select**: Emits the URI of the selected entity as a DOM event.
  - **Copy**: Copies the URI of the selected entity to the clipboard.
  - **Open**: Opens the URI of the selected entity in a new browser tab
  
  ```
() => <GeovAuthorityLookup displayCopyBtn={true} displayOpenBtn={true} displaySelectBtn={true}></GeovAuthorityLookup>

<- ADD THE FOLLOWING TEXT HERE ->

```

The buttons have this behavior:
- **Select**: Emits the URI of the selected entity as a DOM event.
- **Copy**: Copies the URI of the selected entity to the clipboard.
- **Open**: Opens the URI of the selected entity in a new browser tab
