### ISSUE TITLE
Improve documentation of webcomponents

### ISSUE THREAD

**Issue by perrauda** [geovistory/design-system#60]
As the webcomponent can also be used by external developers, good documentation is essential.

In Storybook, the component pages should open on "docs" tab by default.

The docs should contain:

- [x] Manual: initial description of the use of this component (manually created)
- [x] Auto: Code example, show code is expanded by default
- [x] Auto: Playground (link to canvas)
- [x] Manual: Examples ("stories"), show code is expanded by default
- [x] (Optional, if not too complex)Auto: component api 
- [x] Auto: Integration (Link to Getting Started)
- [x] Auto: Theming (Link to Theming)
- [x] Auto: footer with GitHub link

Autogenerated files that are not used for development should be gitignored:
- [x] */readme.md

The "Examples" (stories) should show, how the component's API can be used. Ideally, the examples cover the most important use cases of the component.

In the case of authority-look-up compontent we can explain each one of these props:

- apis
- types
- nbOccurencesMax
- displaySelectBtn, displayOpenBtn, displayCopyBtn
- nbColMax

To make it easier for external developers to understand, we can also add chunks of requests that are executed by the 3 apis (Wikidata, IdRef, GND) queried by the component.

**Comment by joschne** [comment]
The component pages should open on "docs" tab by default.

The docs should contain:

- [ ] Manual: initial description of the use of this component (manually created)
- [ ] Auto: Code example, show code is expanded by default
- [ ] Auto: Playground (link to canvas)
- [ ] Manual: Examples ("stories"), show code is expanded by default
- [ ] (Optional, if not too complex)Auto: component api 
- [ ] Auto: Integration (Link to Getting Started)
- [ ] Auto: Theming (Link to Theming)
- [ ] Auto: footer with GitHub link
