### ISSUE TITLE
Storybook with webcomponents (instead of react)

### ISSUE THREAD

**Issue by flicksolutions** [geovistory/design-system#62]
- Bump Storybook to V 7
- Setup Storybook with webcomponents
- Update current stories
- Analyse _stencil.dev.config.ts_
   - remove unneccesary output targets

**Comment by joschne** [comment]
@flicksolutions: Alexandre and me continued to work on this. We are close to a good solution. therefore the assignment of @perrauda

**Comment by joschne** [comment]
@perrauda please create a PR and link it to this issue
