### ISSUE TITLE
Add RDF-download buttons to entity page

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#68]
Add the [rdf download button](https://design.geovistory.org/?path=/story/data-components-entity-download-rdf--entity-download-rdf) to the [entity card](https://design.geovistory.org/?path=/story/data-components-entity-entity--ship-voyage).

According to this mockup

<img width="792" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/cefa969b-64a9-47af-94cd-3cf9192455b6">

**Comment by perrauda** [comment]
Added and improve geov-download-rdf-button with an additionnal Prop (_projectId_)
