### ISSUE TITLE
Extract color hex-code into css variable

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#72]
The background colors of geov-class-distri and geov-property-distri are set with a hex-code.

This has to be extracted to a css variable.

_Originally posted by @joschne in https://github.com/geovistory/design-system/pull/69#discussion_r1267963266_

**Comment by flicksolutions** [comment]
I suspect, that the color was chosen only by eye and not according to a specific design. This is why I propose to just use var(--background). Using this variable from ionic design, we will have the same background color in multiple places. I'm creating the PR now...
