### ISSUE TITLE
Handle long entity labels

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#77]
The goal of this issue is to find a way to properly display long entity labels `geov-entity-label` as embedded in `geov-entity`.

Instead of 
<img width="713" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/5a46dada-9efb-49e7-bc5a-1419eee03d25">

It should be
<img width="740" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/668b2457-d4ed-490b-83ed-89199e86cd32">

should be as simple as removing white-space:no-wrap, overflow:hidden, text-overflow:ellipsis.

**Comment by flicksolutions** [comment]
added a comment in packages/design-system-web/src/components/geov-entity/geov-entity.css for this. review still in progress.
