### ISSUE TITLE
Add icon to geov-entity

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#79]
The header of a geov-entity should show an icon for some classes (e.g Person, Group, Geographical Place).

<img width="844" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/3be032f2-2b92-48ef-90f7-10142f7f0fad">

As the component can display any class, it must still work for classes that have no icon specified. The alignment of the icon must work on all display sizes.

**Comment by perrauda** [comment]
Added a new component: **Entity Class Icon**
This component return an icon corresponding with class label
(Here, a person)
![Image](https://github.com/geovistory/design-system/assets/5019779/7f6e6b7d-d5dc-4f0f-b03b-b56ab68be84e)

the size is not managed directly, it must be managed by the webcomponent which uses this webcomponent

Here in geov-entity


![Image](https://github.com/geovistory/design-system/assets/5019779/04759753-c56d-4ce2-adb7-8903bb0091e4)

I'd be delighted to hear your views on the placement of the icon

Implemented for:
Person

![Image](https://github.com/geovistory/design-system/assets/5019779/139c454e-2ffd-4f08-997c-fc17a3caa6e4)


Geographical Place

![Image](https://github.com/geovistory/design-system/assets/5019779/028914bf-28da-4817-b73f-ce0563e0dc07)


Group

![Image](https://github.com/geovistory/design-system/assets/5019779/164258bc-1afd-4b90-9dfe-825587ad7e97)


Ship Voyage

![Image](https://github.com/geovistory/design-system/assets/5019779/c10b61b8-5934-40c1-b121-9577b0c382c3)


Date Time Description

![Image](https://github.com/geovistory/design-system/assets/5019779/3106c87a-6fdf-4c81-aa86-d667aee7daf3)

**Comment by perrauda** [comment]
Text


![Image](https://github.com/geovistory/design-system/assets/5019779/d6bfdda7-df09-4d6f-a4fd-ccd764e6f97b)

**Comment by flicksolutions** [comment]
I added some comments in my pending request to this.
I'm going to review the rest of the tickets later - that's why the review isn't finished.
