### ISSUE TITLE
Improve visual design of properties on entity cards

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#80]
he eye is challenged by visual design. This may be because of the columns and/or the big amount of white space. 

The goal of this issue is to experiment and try to find better solutions.

One inspiration can be ontoexplorer, see [this](https://ontoexplorer.geovistory.org/?state=eyJ1c2VkRW5kcG9pbnRzIjpbImh0dHBzOi8vc3BhcnFsLmdlb3Zpc3Rvcnkub3JnL2FwaV92MV9wcm9qZWN0XzkyNDAzMyJdLCJ2aWV3VHlwZSI6MSwiY3VycmVudElyaSI6Imh0dHA6Ly9nZW92aXN0b3J5Lm9yZy9yZXNvdXJjZS9pODM2NzU5IiwiY2xhc3NIaWVyYXJjaHkiOlsiaHR0cHM6Ly9vbnRvbWUubmV0L29udG9sb2d5L2MyMSJdfQ==) example vs [this](https://www.geovistory.org/project/924033/page/i836759?p=924033).

The issue has to be resolved with #52 in mind.

**Comment by joschne** [comment]
@perrauda I think this issue is resolved by PR #98, #102 and #109 

If you agree, please close the issue

**Comment by perrauda** [comment]
Agree
