### ISSUE TITLE
Improve display of long string literals

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#82]
Of long string literals we can currently only see the first line.

Instead of [this](https://www.geovistory.org/project/924033/page/i2346544?p=924033):
 
<img width="927" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/d9421055-a5ac-4bb0-a4cf-757922a43ed9">

it should show the full text. Currently the length of the strings seems to be limited, but there will be really long texts in the future. The display should take this into consideration, e.g. by showing some lines first and allowing to extend the view or to open a popup with the entire text.

**Comment by flicksolutions** [comment]
added comments concerning that in my reviw of #84 aswell.
