### ISSUE TITLE
Fix geov-entity for embedding in website

### ISSUE THREAD

**Issue by joschne** [geovistory/design-system#92]
**Problem 1: Download RDF Button icons**
Icons do not appear:
<img width="620" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/a8b903b1-9e3c-4c30-88cb-b18fbfd17fc4">

**Solution 1**
use "icon" attribute in ion-icon.

**Problem 2**
Class Label is rendered twice. 

<img width="876" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/864dc219-254f-432c-9e80-de5082ea8742">

The problem seems to be caused by inproper hydration: 
<img width="583" alt="image" src="https://github.com/geovistory/design-system/assets/10991869/59a73bd2-4fea-4f43-a873-d19d6ed52aaa">

The string `"Person"` (rendered on server side) is not removed / attatched to the slot. It is unclear why.

**Solution 2**

Add two tests for component `geov-entity-class-label` that reproduce the problem.

Test 1:
(as in `geov-entity-download-rdf.spec.tsx` lines 62ff.)

Render the geov-entity-class-label server side 

Test 2:
(as in `geov-entity-download-rdf.spec.tsx` lines 123ff.)

- Use the output of test 1 as input of test 2.
- Test the hydration and hopefully reproduce the bug

Then figure out a solution. Maybe it is enough to wrap the content of the component in a div.

**Comment by perrauda** [comment]
Update: Tests of geov-entity-class-label are passed (no bug), so I'll create two news tests in geov-entity.

**Comment by joschne** [comment]
issue is resolved by this [commit](https://github.com/geovistory/design-system/commit/bc2a89ff8bc1bec3bc725d0fe362666449a3a00c).

Solution: Change the <p> to <div> resolved the issue.
